version: '3'

# Specifying for Keycloak and Mysql
volumes:
  postgres_data:
    driver: local
  mysqldata:
    driver: local

services:
  # db service for normal API CRUD operations, i.e., db for our Authentication Layer.
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobank
    ports:
      - "5430:5432"

  # Here, starting for Keycloak configurations for our Authentication Layer
  postgres:
    image: postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/postgres_data
    environment: 
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: POSTGRES_PASSWORD

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: DB_PASSWORD
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres
    command:
      - start-dev

  # Include the MySQL service from the external YAML file
  mysql:
    extends:
      file: mysql-service.yaml
      service: mysql